import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'

async function images(page: Page, count = 23) {
  return page.evaluate((count) => Array.from({ length: count }, (_, i) => {
    const canvas = document.createElement('canvas')
    canvas.width = 600; canvas.height = 900
    const ctx = canvas.getContext('2d')!
    ctx.fillStyle = '#f4efe5'; ctx.fillRect(0, 0, 600, 900)
    ctx.strokeStyle = '#486842'; ctx.lineWidth = 8
    ctx.beginPath(); ctx.moveTo(300, 760); ctx.lineTo(300, 170 + i * 2); ctx.stroke()
    ctx.fillStyle = `hsl(${90 + i * 4}, 35%, 35%)`
    ctx.beginPath(); ctx.ellipse(245, 400, 60 + i, 120, -.6, 0, Math.PI * 2); ctx.fill()
    ctx.fillStyle = '#292722'; ctx.font = '32px serif'; ctx.fillText(`Test plate ${i + 1}`, 170, 840)
    return canvas.toDataURL('image/png')
  }), count)
}
async function importPack(page: Page, pack: unknown) {
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.getByRole('tab', { name: 'Import', exact: true }).click()
  await page.locator('.file-drop input').setInputFiles({ name: 'plates.lumen.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(pack)) })
  await expect(page.getByRole('heading', { name: 'Decks', exact: true })).toBeVisible()
}

test('23 image prompts survive reimport, review, undo, export, backup restore and offline reload', async ({ page, context, browserName }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Start with an empty library' }).click()
  const plates = await images(page)
  const pack = { format: 'lumen-deck', version: 1, deck: { id: 'plates', title: 'Botanical plates', cards: plates.map((frontImage, i) => ({ front: 'Identify this plant', back: `Species ${i + 1}`, frontImage, backImage: plates[(i + 1) % plates.length] })) } }
  await importPack(page, pack)
  await importPack(page, pack)
  await page.getByRole('button', { name: /Botanical plates/ }).click()
  await expect(page.locator('.library-card')).toHaveCount(23)
  await expect.poll(() => page.locator('.library-card img').evaluateAll((imgs) => imgs.every((img) => (img as HTMLImageElement).naturalWidth === 600))).toBe(true)
  await page.getByRole('button', { name: 'Study 20 due' }).click()
  await expect(page.getByRole('img', { name: 'Front image', exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Back image', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Enlarge front image' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('img', { name: 'Front image enlarged' })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Show answer' }).click()
  await expect(page.getByRole('img', { name: 'Back image', exact: true })).toBeVisible()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.screenshot({ path: `test-results/image-review-${browserName}.png`, fullPage: true })
  await page.getByRole('button', { name: /Good/ }).click()
  await page.getByRole('button', { name: 'Undo last answer' }).click()
  await expect(page.getByRole('img', { name: 'Back image', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'End review' }).click()
  await page.getByRole('button', { name: 'Decks', exact: true }).click()
  await page.getByRole('button', { name: /Botanical plates/ }).click()
  await page.getByRole('button', { name: 'Deck options' }).click()
  const exportDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Lumen deck' }).click()
  const exported = JSON.parse(await readFile((await (await exportDownload).path())!, 'utf8'))
  expect(exported.deck.cards).toHaveLength(23)
  expect(new Set(exported.deck.cards.map((card: { frontImage: string }) => card.frontImage))).toEqual(new Set(plates))
  await page.getByRole('button', { name: 'Export for Anki' }).click()
  await expect(page.locator('.toast')).toContainText('cannot preserve images')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const backupDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save a full backup' }).click()
  const backupPath = (await (await backupDownload).path())!
  const backup = JSON.parse(await readFile(backupPath, 'utf8'))
  expect(backup.cards).toHaveLength(23)
  expect(backup.cards.every((card: { frontImage: string; backImage: string }) => card.frontImage.startsWith('data:image/png;') && card.backImage.startsWith('data:image/png;'))).toBe(true)
  page.on('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Erase all Lumen data' }).click()
  await page.getByRole('button', { name: 'Start with an empty library' }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.locator('.settings-row--file input').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)) })
  await expect(page.locator('.toast')).toContainText('Restored 23 cards')
  await page.getByRole('button', { name: 'Decks', exact: true }).click()
  await page.getByRole('button', { name: /Botanical plates/ }).click()
  await expect(page.locator('.library-card')).toHaveCount(23)
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  if (browserName !== 'webkit') await context.setOffline(true)
  await page.reload()
  await page.getByRole('button', { name: /Botanical plates/ }).click()
  await expect.poll(() => page.locator('.library-card img').evaluateAll((imgs) => imgs.length === 46 && imgs.every((img) => (img as HTMLImageElement).naturalWidth === 600))).toBe(true)
  await page.getByRole('button', { name: 'Study 20 due' }).click()
  await expect(page.getByRole('img', { name: 'Front image', exact: true })).toBeVisible()
})

test('creates and edits image-only cards and rejects corrupt or tracking images without importing anything', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Start with an empty library' }).click()
  const [front, back] = await images(page, 2)
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.getByLabel('New deck name').fill('My images')
  await page.getByLabel('Front image (optional)').setInputFiles({ name: 'front.png', mimeType: 'image/png', buffer: Buffer.from(front.split(',')[1], 'base64') })
  await page.getByLabel('Back image (optional)').setInputFiles({ name: 'back.png', mimeType: 'image/png', buffer: Buffer.from(back.split(',')[1], 'base64') })
  await page.getByRole('button', { name: 'Add card', exact: true }).click()
  await expect(page.locator('.toast')).toContainText('Card added')
  await page.getByRole('button', { name: 'Decks', exact: true }).click()
  await page.getByRole('button', { name: /My images/ }).click()
  await page.getByRole('button', { name: 'Edit image card' }).click()
  await page.getByLabel('Extra note').fill('Remember the leaf shape.')
  await page.getByRole('button', { name: 'Save card' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.library-card img')).toHaveCount(2)
  await page.getByRole('button', { name: 'Study 1 due' }).click()
  await page.getByRole('button', { name: 'Show answer' }).click()
  await expect(page.getByText('Remember the leaf shape.')).toBeVisible()
  await page.getByRole('button', { name: 'End review' }).click()
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.getByRole('tab', { name: 'Import', exact: true }).click()
  const requests: string[] = []
  page.on('request', (request) => { if (request.url().includes('tracker.invalid')) requests.push(request.url()) })
  for (const frontImage of ['https://tracker.invalid/image.png', 'data:image/png;base64,' + Buffer.from([137,80,78,71,13,10,26,10,...Array(30).fill(0)]).toString('base64')]) {
    await page.locator('.file-drop input').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ title: 'Bad deck', cards: [{ front: 'Valid', back: 'Card' }, { front: '', back: 'Bad', frontImage }] })) })
    await expect(page.getByRole('alert')).toBeVisible()
  }
  expect(requests).toEqual([])
  await page.getByRole('button', { name: 'Decks', exact: true }).click()
  await expect(page.getByRole('button', { name: /Bad deck/ })).toHaveCount(0)
  await page.getByRole('button', { name: /My images/ }).click()
  await expect(page.locator('.library-card')).toHaveCount(1)
})
